FIGURES = ['ackley.pdf', 'dyna.pdf', 'kine.pdf', 'likelihood.pdf', 'mcmc.pdf']

rule target:
    input:
        'paper.tex',
        'handout.bib',
        FIGURES
    output:
        'paper.pdf'
    run:
        shell(
            """
            pdflatex -interaction=nonstopmode -halt-on-error paper.tex
            bibtex paper.aux
            pdflatex -interaction=nonstopmode -halt-on-error paper.tex
            pdflatex -interaction=nonstopmode -halt-on-error paper.tex
          """
        )

rule figures:
    input:
        'plots.py',
        '_fig_params.py'
    output:
        FIGURES
    run:
        shell(
            """
            python plots.py
            """
        )