FIGURES1 = ['ackley.pdf', 'dyna.pdf', 'kine.pdf', 'likelihood.pdf', 'mcmc.pdf']
FIGURES2 = ['phase_problem_ACF.pdf', 'phase_problem_SLD.pdf']

rule target:
    input:
        'paper.tex',
        'handout.bib',
        FIGURES1, 
        FIGURES2
    output:
        'paper.pdf'
    run:
        shell(
            """
            pdflatex -interaction=nonstopmode -halt-on-error paper.tex
            bibtex paper.aux
            pdflatex -interaction=nonstopmode -halt-on-error paper.tex
            pdflatex -interaction=nonstopmode -halt-on-error paper.tex
          """
        )

rule figures:
    input:
        'plots.py',
        '_fig_params.py'
    output:
        FIGURES1
    run:
        shell(
            """
            python plots.py
            """
        )

rule figures2:
    input:
        'phase_problem_figs.py',
        '_fig_params.py'
    output:
        FIGURES2
    run:
        shell(
            """
            python phase_problem_figs.py
            """
        )