name: build
on: 
   push:
     paths:
       - refl_maths/*  
   pull_request:
     paths:
       - refl_maths/*

jobs: 
  build:
    name: Create Paper
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Testing
        uses: snakemake/snakemake-github-action@v1.9.0
        with:
          directory: './'
          snakefile: 'Snakefile'
          args: '--cores 1 '
          stagein: |
            apt-get -qq update && apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended texlive-publishers texlive-science-doc texlive-science
            pip install --user matplotlib emcee numpy scipy seaborn refnx==0.18
            cd refl_maths
      - name: Update release
        uses: johnwbyrd/update-release@v1.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release: paper
          tag: paper
          files: refl_maths/paper.pdf
